//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Project3D : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose LeftController
        {
            get
            {
                return SteamVR_Actions.project3D_LeftController;
            }
        }
        
        public virtual SteamVR_Action_Pose RightController
        {
            get
            {
                return SteamVR_Actions.project3D_RightController;
            }
        }
        
        public virtual SteamVR_Action_Boolean Trigger
        {
            get
            {
                return SteamVR_Actions.project3D_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Locomotive
        {
            get
            {
                return SteamVR_Actions.project3D_Locomotive;
            }
        }
        
        public virtual SteamVR_Action_Boolean LocPush
        {
            get
            {
                return SteamVR_Actions.project3D_LocPush;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.project3D_Grab;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.project3D_Haptic;
            }
        }
    }
}
